### ISSUE TITLE
Code coverage is not 100% for Central-services-auth on CircleCI builds

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/central-services-auth#4]
**Goal**:
As a developer I want code coverage of unit tests to pass 100%.

**Tasks**:
- [ ] Update unit tests for 100% code coverage for bearer.js
- [ ] Test code coverage to ensure 100% for bearer.js has been achieved

**Acceptance Criteria**:
- [ ] Code Coverage is failing as per the following report output:
=============================== Coverage summary ===============================
Statements   : 73.97% ( 54/73 )
Branches     : 53.33% ( 16/30 )
Functions    : 100% ( 2/2 )
Lines        : 73.97% ( 54/73 )
================================================================================

The cause that bearer.js only has 4/23 tests passed for code coverage. Unit tests for bearer.js need to be updated for 100% pass (23/23).

**Dependencies**:
n/a

**Comment by elnyry-sam-k** [comment]
Use mojaloop/project/issues to track issues now
